apiVersion: v1
kind: Service
metadata:
  name: service-hpa
  namespace: nazim
spec:
  selector:
    app: hpa-dp
  ports:
  - port: 8080
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-dp
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: hpa-dp
  template:
    metadata:
      labels:
        app: hpa-dp
    spec:
      containers:
      - name: hpa-dp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  namespace: nazim
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-dp
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

