apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nazim
  name: my-nginx2
spec:
  selector:
    matchLabels:
      app: my-apache
  template:
    metadata:
      labels:
        app: my-apache
    spec:
      containers:
      - name: my-apache
        image: httpd
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: nazim
  name: my-svc-apache
spec:
  type: NodePort
  selector:
    app: my-apache
  ports:
  - port: 9001
    targetPort: 80

