apiVersion: apps/v1
kind: Deployment
metadata:
  name: task3-3
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: task3-3
  template:
    metadata:
      labels:
        app: task3-3
    spec:
      containers:
      - name: task3-3
        image: vaheye/task3.3:2.0
        ports:
        - containerPort: 80
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-task3-3
  namespace: nazim
spec:
  type: LoadBalancer
  selector:
    app: task3-3
  ports:
  - name: apache
    port: 8081
    targetPort: 80
  - name: postgres
    port: 5432
    targetPort: 5432

