---
apiVersion: v1
kind: Pod
metadata: 
  name: curl
  namespace: nazim
spec:
  containers: 
  - name: curl
    image: curlimages/curl
    securityContext:
      runAsUser: 0
    command: ['sh', '-c', 'while true; do sleep 10; done']