apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nazim
  name: mysql
data:
  username: user
  password: '134568'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nazim
  name: mysql-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql1
  template:
    metadata:
      labels:
        app: mysql1
    spec:
      containers:
      - name: mysql-dep
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql
              key: password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql
              key: username
        ports:
        - containerPort: 3306

