apiVersion: v1
kind: Secret
metadata:
  namespace: nazim
  name: ssh-secret
type: Opaque
data:
  ssh-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBNFFDTDBNVTdpWUtCbCtGR28vcjdYeG1KejNaeHhCVmpnSFhoRjg0WE1vMitobENmClJrOXNxMDc0WEJiVGNMYWE1cDlNanRMMktKdXJ6UUpJa0lsL2UvNHdVdHhLbzROYkJTcTg5WGRmMkljcHJjcUQKcG8vVFFsNW1kS0hEK1ZmK2h3TXdhWVVWWlAvR0ZiZWIzVytwbWNuZ1hxZTh1bWJpSjJORi9oeng3a09RR2xIcQpFdjVncmR0SkJoMmMydEZjRHZYU0dvR1E3UTFHeEdSU2xkb2JkM2ZhakFacjROSTVTREpYSGJxeGlZT00yeTBhClg5T0EvK3BueHkvMkk4b3p1U01zdkx3SXNFYUI5T0tEQWU1R0liWEJ3SmlZQkhJVmdReDlDZ2ZIOFdCcEl0SGEKYmJ2Z0FyaUd0RGVvVkQ5S1ZHSDNYMUMxellPSjgzaCtRb0ltQ1FJREFRQUJBb0lCQUdrV1NUYnp0Mi90SFR2agpnb3U2QUVlVmRQRUpuKzcyRW1nQUptWm80aHJCYXhmdWRjVnYrUkExclBmTnpXbGFVQlNnbURBb3hjR0htNEQvCnJRYWN3WWNXM0ZrRy9IRk1PMm01WVZIQU5HcThEakpXWUpDZG9nemdiRGZUQ2VYZVBFbXdxcDdPQW9VT2xPUzEKd2IxMWxwLzJVcTNDNS9tamJjTDVzY29TbU1ndnM4SmhEUENieVFHcWpIazFZT1dFUDYyRVdDMWNCcFZCMUlTMQp6QlBQREdFYlFJYU9TUlZCcmZuNEU3UTVsUVMxWVFRWGFDaHhxakd0ZG94OXhqRi8xd2VsUXFvVGpNaWxhSzNxCnR3R05zWUZTSVpaa0kxL2pYQkFiWmluTzhVb1FJbjJmN2xjMjZLQjN3UDliRkdacW9NR1d3UmQzQXNsbUdrbFQKMkVMWWoxVUNnWUVBOS9pUWFOSXZ6U24wRk9HUXBKb1EwR1o2ekFWZFNRVUJxY0hsNjFhZmlMcmRJTUNBRENoaQpoaURGT3Z1K0NVbnh6K25VeSttSE8wVHlBOTM1NnNjWk9YRjIxN1VXS2NWL29Cc2J0dVhJeitKbVl4NExEZ2JOCjh5MWVHQ1J3YVQrVmt6aG00aEJUVTYxdUpzVXVlY3lNenpVOVdRb2ZTNGxHNWd6S3VNY3A1WDhDZ1lFQTZFbVgKMDU3S1hUMkpNamlmMnBBdCtQOHZjZVFwdmlYaHpDUm53OU9TZExHTkJWNmtNV2dzWE9kVDFvVTMxZStjUXYrSwo3L2FyN2VzbHIzV1hOTmZQbDVwTFZtSEh1Q0FUZ2FJMjArY01kRkxWWjV6eGQvNEF4T3MzY2dhZ1hrYTZHSE1rClJmbzVFZElZdmRTVzlGTHVhYWdnR3RiVHhrLzR6RGZhdGxSamlIY0NnWUFNeGhFcVZTbUJPQmdLdTFQb0pzZVcKOUxCK3NnZ01LdVhiQ05IL1BZY2FWQVh3R2ZwK3BkWHRjdUsyRnlIQytMd3NLYTk4a1pzVndvZDFDNHBFUGQxZQp5Q21IRXgwQktkdFpOQXhKYjZ6WWlLRWRtZjZYeW1IeGxQU3o2YXlndjFYRkw3S2RFcG80UlViWFdIRDhkVDBMCnI0SnBnOHY0NkNsdTBGbmhDdUZ0b1FLQmdRQ1Rqa1E2OHJDOEFCNEozL3h6bTRrSWxobnVjREN3RUdKYUNubzcKNUVjeGg2UDhXRDFYQVVURkUxR25nT0tTTE82SGhNc2VXZ1NuVXV1U2hORXppUy9lcnUzU2hyU1cyeEZwRk1GZApaSFQ5NDZ5YWNCRFgxMnRucTcrQjJJSEF3WTd2Znh6NHN0WFQ0ekZDVFN4RE1mY3UrTlRFRjlsWkxXM3ZWRC9ECitPRnRTd0tCZ1FDcHo2MkEyaTNRY1hQTHorTG9QTTJsbWprNVpSU05YeGdiTGZkK3ZuZjF2WHYxU1Y5b2VTWTUKS2diODVmdFJ6RlBSVFNMVzV6RkE5T3RmTHdmZnI1NUg1MWcyLzZUQWxOdG1uSHdBSUVBTmtBa0owZWthaUQ5Ugo3RUhKRGw5LzA4ekxGWTR5bFJQaTNxSnhsSm5Famk1cHNYblRhQ3B0TDlONnh4UlVNMlJUNXc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nazim
  name: ssh-dep
spec:
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
      - name: ssh-dep
        image: alpine/git
        env:
        - name: SSH_KEY_GIT
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: ssh-key
        command:
        - "ash"
        - "-c"
        - "while true; do sleep 3600; done"

