apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZyekNDQTVlZ0F3SUJBZ0lVUVhDYkJRR3FiTnNMOVpGZmZ5TEJCb1NiUG1Vd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1p6RUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERWdNQjRHQ1NxR1NJYjNEUUVKQVJZUllXNTBkR1ZqCmFFQm5iV0ZwYkM1amIyMHdIaGNOTWpNd016QTVNRFV6TkRNMFdoY05NalF3TXpBNE1EVXpORE0wV2pCbk1Rc3cKQ1FZRFZRUUdFd0pCVlRFVE1CRUdBMVVFQ0F3S1UyOXRaUzFUZEdGMFpURWhNQjhHQTFVRUNnd1lTVzUwWlhKdQpaWFFnVjJsa1oybDBjeUJRZEhrZ1RIUmtNU0F3SGdZSktvWklodmNOQVFrQkZoRmhiblIwWldOb1FHZHRZV2xzCkxtTnZiVENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQkFMMXd2ZVZXQWo1ODNVeU0KbXltQXFKejdCQ2RuSzhQS0t0anVwRVRwWjBBMlNoSnhOaVhEZ2liVHFyb0E1a29vRzNLcDYrM1NxUUxJNFlMRwp1WGFINzVwNExQRDNrQmRaWG4zbktPY1U2WjAvWmxZR2FmVnVDLytSSG8xRENFc3kyeFN1SElrQ1gvWEZNMEdzCnphbnFCTFcxZWdNbFNUQXhnd1k4cVBEclNpc2NwVmpZVi96c2pIeWhKa2UxdzRqTTQyVTRGTHNjb0VGcHcxM2kKTHNZc004Mk5BUWttb3UzZFNhMEZ3UUVkZVRTSkhKd0hySXl0QU9DYmhaZzc4QnNpZ1FVQ2UwYTY3UUVYWFZINQpkZ045eVVrbzcrVVVIWmtNc08vWUVDYUtEUGhHL0pIZjBtWTNGOTEyaXJlZFpNUlB6UDkvdGYxRUdKUks5M0NsCkIxZzk4ck11ejdOZ0VmV2MwWkZ2TDkvcnZZbFpLN1lVMkxDM29XbHhTSktMR29lU3YxUVVJYUlZVnRja2VDZHEKNllpVkpMQ2RIdlJxdGtTR0JIRG1QVW03eW5teXFhUDd4cVhPZFhSS3lRUU54OFRDWVIydjdVZFhpRE9PZW9kbApGS0creFVJUVZWa09aSnVQL21qS3NyeGJvOFZ4cWxRWms0STdadm51WFNmRC9NZG9xL1FKRkF1aEdUWlU2UFp1CmY5Szg3SWVCYXVBSUdPZlErZGhLNEU2UVhkc1l3b1FFV0plR3NISmhmYldKM0ZJTnVGTzlZaTdxNmd4Skt4aTcKRU0vTFhBWEY3VWdnN2tvby94Q1pvT3FjdHhJZU02d2VNUU9vUHFYT2FUM0FLbko5M0lxWmw5OENuSHpIWXZmRAphcVZUQ3EybmRoN2Y5cW1ORzdvK01MME15c2hwQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJUSFZHbllkT3UxClMwaHJKRFFLNTMra3pUTGkxekFmQmdOVkhTTUVHREFXZ0JUSFZHbllkT3UxUzBockpEUUs1MytrelRMaTF6QVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJ4aUVaSFpaN1BoSHRoNC9aTApVTEg0dkUzSGxTTjkrQ3o3WXc2a255SEVPU0R0bk9qc1JGSitYMHJkNWtsdGpFRHFrZnU2a2xCL3Z2YlUvWXR1CmwwZCsydlFkVkRlaDRoakY4L3lUMFVMYnYxbGorRmo0S0IxWjFnSTJoeGhWOFZ5alh1SUttL1M3VEtJdUtLTk4KZUlXdE5WZk5SNHY0bHQ1WXJ5NElxWlErdjExamRQMGtkK0o5VG0vMmUxdzB3NzZ2Q3NNMFVCZVc4NmtULy9ubApzeks0ejNETXhLVmkvTFpiNmUyRTErUmFybThFMkMyN29XL3BDMVFSU3V3a0tIZ0FRVko5dFg3RytkVzdsRHdDCmkvdGZ0VWxPRWdWMG1hU2FNWHlGV0wzeldwTW5zcUpEYVlGS2pwanhLVThZY09LRHVOM3NYNlFLRitaRWJXdFEKV21ia2Fob1JFTUxZM1BKeXFYZG5ZOVJQanJWekNPaEUyUlRRZEY4SW1JcFZLd2cvRnMwZ1lURWsyY1Yrb3BPbQpVeHh1T09IU0FIWkhrekszWUZCUDVrUjYwSUNwZkRuOGJLUFlKYnZUem95QUhVd3N0dVlsdnZORUdna09xNTlBClQ2UGptWXpsamlEN2pTVk53OFRpM0VOek1IeU83ZERLaEFiUGt5VWpHRXRJenkwN3BVUTBlNWw3dWJkdFR2ZXAKYmtkUmxYUm12dTgweXppY2I5L2xFdjgzeUp4Q1ZPcG42U3QwbUFNNitSMmNzcEw2c2laU1JHNkZrM1A4UFQ5ago0OXpncnZxN1dnTjJrY0JQRHR0MEowb1dNckZQTU9EU0JkRDdUNHZueSs1blRuS3hmcUZUUkJLZy8zQVZaMG96CnVnUmRienBjdXczMU8yRlFwcXNOK3ZhUGdBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1Mwd2dna3BBZ0VBQW9JQ0FRQzljTDNsVmdJK2ZOMU0KakpzcGdLaWMrd1FuWnl2RHlpclk3cVJFNldkQU5rb1NjVFlsdzRJbTA2cTZBT1pLS0J0eXFldnQwcWtDeU9HQwp4cmwyaCsrYWVDenc5NUFYV1Y1OTV5am5GT21kUDJaV0JtbjFiZ3Yva1I2TlF3aExNdHNVcmh5SkFsLzF4VE5CCnJNMnA2Z1MxdFhvREpVa3dNWU1HUEtqdzYwb3JIS1ZZMkZmODdJeDhvU1pIdGNPSXpPTmxPQlM3SEtCQmFjTmQKNGk3R0xEUE5qUUVKSnFMdDNVbXRCY0VCSFhrMGlSeWNCNnlNclFEZ200V1lPL0FiSW9FRkFudEd1dTBCRjExUgorWFlEZmNsSktPL2xGQjJaRExEdjJCQW1pZ3o0UnZ5UjM5Sm1OeGZkZG9xM25XVEVUOHovZjdYOVJCaVVTdmR3CnBRZFlQZkt6THMrellCSDFuTkdSYnkvZjY3MkpXU3UyRk5pd3Q2RnBjVWlTaXhxSGtyOVVGQ0dpR0ZiWEpIZ24KYXVtSWxTU3duUjcwYXJaRWhnUnc1ajFKdThwNXNxbWorOGFsem5WMFNza0VEY2ZFd21FZHIrMUhWNGd6am5xSApaUlNodnNWQ0VGVlpEbVNiai81b3lySzhXNlBGY2FwVUdaT0NPMmI1N2wwbncvekhhS3YwQ1JRTG9SazJWT2oyCmJuL1N2T3lIZ1dyZ0NCam4wUG5ZU3VCT2tGM2JHTUtFQkZpWGhyQnlZWDIxaWR4U0RiaFR2V0l1NnVvTVNTc1kKdXhEUHkxd0Z4ZTFJSU81S0tQOFFtYURxbkxjU0hqT3NIakVEcUQ2bHptazl3Q3B5ZmR5S21aZmZBcHg4eDJMMwp3MnFsVXdxdHAzWWUzL2FwalJ1NlBqQzlETXJJYVFJREFRQUJBb0lDQUZoSFRYYXRtZVljc2RPV1FrZ1kySG91CnowUzlZenVkM2xHeEE0UEpjSUFQekh6RG5RUUVFNGFjWkpiQkRJL0tHT0JhSnNOd3c2bTBpc0l5Y1FLM1hnU1IKcy8rbW5kTURwbkR0WTdZcm5LSFdoWTNZOTArVHRLdW5xS0VUZDYzelNQeGVGcFlTTVQyS1k5UmEvb3dMclo0dgpyMmYvM0JkRk8xV1F0dmx0NitZak56b3J0dlQ2Rm8yTld4Vlhzb0x4VjVZM2lCR1p5V1F5TVFSeS9uRUM4REQ5CllGb3ZVd1dkZFZQWHRwVWFjdnowV0F5dDFzN0hYLzFLKy9weEUvYlJJV2FBUFlvOFdXMkV3Y3dOZjkwb3BNQWUKLzR1MDBBWWVUK1cwdmZIM3F3dVhxT01oZGg2RDFlOHg2bnFlTWZMNWJRSXpOVStNaUJleXg1UUtrMTJmb0pUcApPN3oreEZhdXBRV3E2eWlZVXJOMGsvcVVXUisrNCtSRTUwZ0RBUjFvRlZ4Snpuakhod09NRFd4QTBhcDRRVlZNCmVCM05NbmNiZVIwZGZCdXYrandZZHJmZ1cwQnBYd1lGT0t5ZHV3RWkrdFF5cnUzZkJJejJCREVndnY1Wk9OSDYKVGN3Nzdtb1pqK1IyNXhic3JMb1NRRUJmYnFCV3loZ2pKdEgya25TY2cyck9qK3pTZ1llQmJwRnkrU09WSnNjeAphWjVoSCtYVEliTlpwOHhZbFJ0R3ZkcmF2aEV1NEFLQlM1bEJNT2xnRjhwSmw0VlE3NEd4VVMwZ3EvRUFhK0hTClAvS1h0R3VWLzVTazJ4eURsVFdLcXp0eUkybHJHZXZnSENPVjNjSWRac3QxT0dKUjZnbGFtSktnNCtwcW9aQk4Kc1YydUxuc2pudCtiU1kyWEswTXhBb0lCQVFEeHY5dFprUjlZZlJ4QjZCZlZjSHlmZnFXeVd0UGEzMEZxN21JUQo1TVRpWFlBRCtVT0REOGZUOEtaTHY4MlJtN1BrRnZGRWcxWkNMQVZwZHhGWlBNNE9lTTlnSExqRm1ieHBTenFJCloreTFma0JjaUNrTHhsUDZicDR4ZllCeTRYOFZseFBQSVBCYW5Kb0Z3d20wQkh1bzJGMkVHSzZvZDBnV1h2UFQKTEYvNjhMWkh6MER4akxzNkd4ZGVJZk81eHVrUDlQZDdWbmJDaE1RQlJjTmJUNG1xT1JybzgxMmdESUJ0OHlNMwoyME1kVnRFbHNNMERNMlhZZk4zd2htYjJJR1J4bDBLVEJXOGR0UGEvVnYrS1N5UFR2eng1VjFwVXYvL0NMZlJhCnBQdFRjNzAzbHlUN1lqd1hRUHJaRHkwNUcxWXNKejRXL3ZSK1NOMDF5UjJLbitYckFvSUJBUURJbTRLak5kb3EKTm5JbzRZMm1KbE1jUWlVQXVLUEN6elRjTFBNekJFejBzVk1NSlA2cno3T1Z1Z2YrU2FnbmFlUmRjeFppWWZoeApHOWZtcHJGQ1dVTkdKa3llZER6L2VZTzliSnJDb3ZKU01Vd3lOVE1hQXlmeWwwU1lqQ3hrbTYzbGhWRE01OUJLCjdNNGtidFBaNjNwNmNRcEV2NWtXRFFyU1JLUEFPZFFiZTRwU0J3ajJ0bm9TOE5vd2J0bHRXWHlUbGt6SDY2aVgKQnpiL0NtSGxOWlVweW91cjFZU2hob2NsNHFxZmNKY3BnWUxaWldtL1RaemdsRGs3dW5HVXlBQXEyRWNrTzJEZgo4VUltMzNNZEFLamFCZDdpWXhIOE1FeE9GWUJOTTNPbTduSGhQKzhuV0pweEpjelNTNHhka0kvWiszWVFRQ2R4CnB4UjVGclZVajFIN0FvSUJBUURQcVdiYkFYWlRwT1RwR0YyZzB3ZTZXaWdybFNuM0VXQTRZcDJLdFhrS21oYWwKVXpGVEcvTWpjOHpsdE5UNUJ5NzM5MTA0NVRqcmpyVDNhM2hUbDQvSmpxMVVlbGVlSmZsYTJXeG1VQjlkcUIzUgpYb1Vqd0RIVEpjSnQ4TWl0NWxZc1RhS09nbFQxQVNDdFltU3JaazV6TTZqaEYvS3dkQVpRY1RBeGJpVGtnbkdTCkxjNHpzQmdFU2RGQTR4bGh0Q1B2dVJYOXRNQS9SNXkzR3g0OUNZM1AwMDN5WFZ0SGFIWEovTmw3MmJWRk5wWmkKTWdWcGduVXlDZEQ4RS9mTjVQVmpQZlBLSnhqVUErY1JaY0lOSVk2ZERlRDh1clMxcUZnaWpTY2gxaWF1QVBYQgpFdXlKcEZES0NOOXlKVDlMbHRmbkJhNm9Ra256VU5QMHA5WGdob29SQW9JQkFRQ1dScGg0TnZFMVNnLyt1K2htCm5MTUpxaXNaL1RiL3lrVG80dXRVUGxaL3Z3NWRQS0ZpaDNjYUpIKzBaKzBGaVhlKzRXWFZVVnJSTUhCdG9sV0wKUkY3Mi85M0puWDNNUzNUNnc0NnpXMmwzVk9LbGdlREVEYlV4TDB2OWtwUDIwZ0JVdmFlbnQ4ZjdPS1c3K1NITwpUMjR5cHRkd1pLOERLOFg5ZWRuSk9BakNoYXM2ZzNhZGlsaXNNNnpmTjBxOWRabXkzWmFxOU1nWVN4bFJ1SzlaCkN1aXdvOEE1ZXZ1ZUhLN0ZIS1dBUnRHV0VDUzdRaE1UY2NxaEdhZytMQTdGeTRVRWszdkhrb3VoZHBOOWwwb2UKWWM0YmRPWmdaS0ttYm0vYTFwU0VRSlRVYWk3NDgvSHRZWnhnUWxiSytqa3VKZ3I4MmppNU43WFVsN3JvY3JCbgpwZTFkQW9JQkFHaUFLKzdsY0w4NjVnSmxYZFpNZkdsQTFpYXRkU2tYZEdjOEs3MFFpOGxaV0tEcTdPa1BHNklFCjNJK0U0QkQ0OTZaKzhDTmZiMDYwc1ZWK0xLbnpIeEdXKzR0YlVuNVdJTmdSQU5tQmdPTSt2dXNqNENJWHgrdzcKbkd3Ui9EMlJrRy9CTGo0SlV6K2tJSm9qcXAyaEt5WGc1WWJhVEpiUHVOaExpM3RkVjQxVWtCVGVjdHN2VlBqNwpYTHdYTVl6QmRSVFZDMFBHWXZ1YjlUWjZqSXlvd21vOWVEL2pZdTlRNExIbmc5Y0M4ME91S3hDakFFWkJkb0NCCllCc3U5ZDFmbVBFVnp4TWlHNGpUdFpTREZaL0NSbHF6bXBQVUZrME5lOWREaTIwNTVKQTNlR1lseGpxVUlEMHQKTnZCNmh3aUpISWk1U3VtNGg5TG9qUGZ4RnhMTnRibz0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: tls-secret
  namespace: nazim
type: kubernetes.io/tls

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: nazim
  labels:
    app: my-service
spec:
  type: NodePort
  selector:
    app: deployment-a
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-a
  namespace: nazim
  labels:
    app: deployment-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-a
  template:
    metadata:
      labels:
        app: deployment-a
    spec:
      containers:
        - name: pod-a
          image: vaheye/nginx443:4
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: tls-secret
              mountPath: "/etc/nginx/ssl"
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            secretName: tls-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-b
  namespace: nazim
  labels:
    app1: deployment-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-b
  template:
    metadata:
      labels:
        app: deployment-b
    spec:
      containers:
        - name: pod-b
          image: vaheye/nginx443:4
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: tls-secret
              mountPath: "/etc/nginx/ssl"
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            secretName: tls-secret