apiVersion: v1
kind: ConfigMap
metadata:
  name: my-script-app
  namespace: nazim
data:
  myscript.sh: |
    #!/bin/bash
    echo "Hello, From Nazim!" > /usr/share/nginx/html/index.html
    service nginx stop
    nginx -g 'daemon off;'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task4-5
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: task4-5
  template:
    metadata:
      labels:
        app: task4-5
    spec:
      volumes:
      - name: script-volume
        configMap:
          defaultMode: 0744
          name: my-script-app
      containers:
      - name: task4-5
        image: nginx
        volumeMounts:
        - mountPath: /config/script
          name: script-volume
        command: 
        - "/bin/bash"
        - "-c"
        # - "chmod +x /config/script/myscript.sh"
        - "/config/script/myscript.sh"
        ports:
        - containerPort: 80
      

