apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dep-1
spec:
  selector:
    matchLabels:
      greeting: hello
      version: one
  replicas: 1
  template: 
    metadata:
      labels:
        greeting: hello
        version: one
    spec:
      containers:
      - name: hello-app-1
        image: nginx:1.23.3
        env:
        - name: "PORT"
          value: "80"

---
apiVersion: v1
kind: Service
metadata: 
  name: hello-world-1
spec:
  type: NodePort
  selector:
    greeting: hello
    version: one
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dep-2
spec:
  selector:
    matchLabels:
      greeting: hello
      version: two
  replicas: 1
  template:
    metadata:
      labels:
        greeting: hello
        version: two
    spec:
      containers:
      - name: hello-app-2
        image: nginx:1.23.3
        command: ["sh", "-c", "mkdir -p /usr/share/nginx/html/v2 && echo Hi it is worked > /usr/share/nginx/html/v2/index.html && nginx -g 'daemon off;'"]
        env: 
        - name: "PORT"
          value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-2
spec:
  type: NodePort
  selector:
    greeting: hello
    version: two
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: akzhol7.ml 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: hello-world-1
            port:
              number: 80
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: hello-world-2
            port:
              number: 80