replicas: 1

image: nginx
nameOverride: "ggg"
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: Prefix

