apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: nazim
  labels:
    app: myapp
spec:
  containers:
  - name: front
    # image: us.gcr.io/eternal-bongo-379210/backendnz:v3
    image: us.gcr.io/eternal-bongo-379210/frontendnz:v1
    # env:
    # - name: PGHOST
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgresnz
    #       key: host
    # - name: PGUSER
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgresnz
    #       key: user
    # - name: PGPASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgresnz
    #       key: password
    # - name: PGDATABASE
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgresnz
    #       key: db
    resources:
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: nazim
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 80
