apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standardnz
  namespace: nazim
provisioner: kubernetes.io/gce-pd
parameters: 
  type: pd-standard
  replication-type: none

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypvnz
  namespace: nazim
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  claimRef:
    namespace: nazim
    name: mypvcnz
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standardnz
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4
    

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvcnz
  namespace: nazim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1.5Gi
  storageClassName: standardnz

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw3-1
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: hw3-1
  template:
    metadata:
      labels:
        app: hw3-1
    spec:
      containers:
      - name: hw3-1
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts: 
        - name: my-vol
          mountPath: /usr/share/nginx/html
      volumes: 
      - name: my-vol
        persistentVolumeClaim:
          claimName: mypvcnz


---


