apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  namespace: nazim
  labels:
    app: nginxrs
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: nginxrs
  template:
    metadata:
      labels:
        app: nginxrs
    spec:
      containers:
      - name: nginxrs
        image: nginx
