apiVersion: v1
kind: Service
metadata:
  name: externaldns
  namespace: nazim
  annotations:
    external-dns.alpha.kubernetes.io/hostname: apache.nazimv.tk
spec:
  type: LoadBalancer
  selector:
    app: dns
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-externaldns
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
    spec:
      containers:
      - name: dns
        image: httpd
        resources:
        ports:
        - containerPort: 80

