apiVersion: v1
kind: Service
metadata:
  name: canary-app
  namespace: nazim
spec:
  selector:
    app: canary
  ports:
  - port: 8080
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  namespace: nazim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary
        image: nginx:stable-perl
        command:
          - /bin/bash
          - -c
          - echo '<h1>hello from old</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary1
  namespace: nazim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary
        image: nginx:stable-perl
        command:
          - /bin/bash
          - -c
          - echo '<h1>hello from new</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80