
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: secret-nazim
type: Opaque
data:
  secret: SGVsbG8gU3lpbXlr

---

apiVersion: v1
kind: Secret
metadata:
  name: secret2
  namespace: secret-nazim
type: Opaque
data:
  user: dXNlcjE=
  pass: MTIzNA==

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: secret-nazim
  labels:
    app: secret-pod
spec:
  activeDeadlineSeconds: 60
  containers:
  - name: secret-pod
    image: busybox:1.31.1
    env:
      - name: APP_USER
        valueFrom:
          secretKeyRef:
            name: secret2
            key: user
      - name: APP_PASS
        valueFrom:
          secretKeyRef:
            name: secret2
            key: pass
    resources:
    command:
      - sh
      - -c 
      - while true; do sleep 3600; done
    volumeMounts:
    - name: secret-volume
      mountPath: /tmp/secret1
      readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: secret
  

