apiVersion: v1
kind: Pod
metadata:
  name: ready-if-service-ready
  namespace: nazim
  labels:
    app: task1
    
spec:
  containers:
  - name: myapp
    image: nginx:1.16.1-alpine
    securityContext:
      runAsUser: 0
    resources:
    ports:
      - containerPort: 80
    livenessProbe:
      exec:
        command:
          - "ash"
          - "-c"
          - "true"
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
          - "ash"
          - "-c"
          - "wget -T2 -O- http://service-am-i-ready:80"
      initialDelaySeconds: 5
      periodSeconds: 10

---

apiVersion: v1
kind: Pod
metadata:
  name: am-i-ready
  namespace: nazim
  labels:
    id: cross-server-ready
    
spec:
  containers:
  - name: myapp
    image: nginx:1.16.1-alpine
    securityContext:
      runAsUser: 0
    ports:
      - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: service-am-i-ready
  namespace: nazim
spec:
  selector:
    id: cross-server-ready
  ports:
  - port: 80
    targetPort: 80
