apiVersion: v1
kind: Pod
metadata:
  name: multi-container-playground
  namespace: nazim
  labels:
    app: multi-container-playground
spec:
  containers:
  - name: c1
    image: nginx:1.17.6-alpine
    env:
      - name: MY_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    ports:
      - containerPort: 80
    volumeMounts:
      - name: pod-vol
        mountPath: /pod-vol
  - name: c2
    image:  busybox:1.31.1
    volumeMounts:
      - name: pod-vol
        mountPath: /pod-vol
    command:
      - sh
      - -c
      - while true; do date >> /pod-vol/date.log; sleep 1; done
  - name: c3
    image: busybox:1.31.1
    volumeMounts:
      - name: pod-vol
        mountPath: /pod-vol
    command:
      - sh
      - -c
      - tail -f /pod-vol/date.log 
  volumes:
    - name: pod-vol
      emptyDir:
        sizeLimit: 500Mi

