apiVersion: v1
kind: ServiceAccount
metadata:
  name: processornz
  namespace: project-hamsternz
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: project-hamsternz
  name: processornz
rules:
  - apiGroups:
    - ""
    resources: 
    - "secretes"
    - "configmaps"
    verbs:
    - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processornz
  namespace: project-hamsternz
subjects:
- kind: ServiceAccount
  name: processornz
  namespace: project-hamsternz
roleRef:
  kind: Role
  name: processornz
  apiGroup: rbac.authorization.k8s.io