apiVersion: v1
kind: Pod
metadata:
  name: env-pod1
  namespace: nazim
spec:
  containers:
    - name: env-pod1
      image: busybox
      env:
        - name: MY_VAR
          value: "Hello World"
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 3600; done"
