apiVersion: v1
kind: Pod
metadata:
  name: hostname-pod
  namespace: nazim
spec:
  containers:
    - name: hostname-pod
      image: busybox
      env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 3600; done"