apiVersion: v1
kind: Pod
metadata:
  name: ip-pod
  namespace: nazim
spec:
  containers:
    - name: ip-pod
      image: busybox
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      command:
        - "sh"
        - "-c"
        - "echo $MY_POD_IP"