apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpolicy-dep
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: nginx-pol
  template:
    metadata:
      labels:
        app: nginx-pol
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pod
  namespace: nazim
spec:
  podSelector:
    matchLabels:
      app: nginx-pol
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: curl
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: mycurl
  namespace: nazim
  labels:
    app: curl
spec:
  containers:
  - name: mycurl
    image: curlimages/curl
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    command:
      - sh
      - -c
      - while true; do sleep 3600; done


