apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpolicy
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: dep
  template:
    metadata:
      labels:
        app: dep
    spec:
      containers:
      - name: dep
        image: nginx
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: nazim
  labels:
    app: dep
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
      - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-deployment
  namespace: nazim
spec:
  podSelector:
    matchLabels:
      app: dep
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080