apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-fluentd
  namespace: nazim
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: my-fluentd
  template:
    metadata:
      labels:
       name: my-fluentd
    spec:
      containers:
      - name: my-fluentd
        image: fluentd
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
