apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: nazim
spec:
  secretName: tls-secret
  duration: 24h
  renewBefore: 12h
  dnsNames:
  - nazimv.tk
  issuerRef:
    name: tls-cert-prod
    kind: Issuer
    group: cert-manager.io