apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: nazim
spec:
  selector:
    app: nginx
  ports:
  - port: 9000
    targetPort: 80
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: nazim
spec:
  selector:
    app: apache
  ports:
  - port: 9001
    targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task5
  namespace: nazim
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/issuer: "tls-cert-prod"
    external-dns.alpha.kubernetes.io/hostname: nazimv.tk
  labels:
    app: task5
spec:
  rules:
  - host: nazimv.tk
    http:
      paths:
      - pathType: Prefix
        path: /nginx
        backend:
          service:
            name: service1
            port: 
              number: 9000
      - pathType: Prefix
        path: /apache
        backend:
          service:
            name: service2
            port: 
              number: 9001
  # tls:
  # - hosts: 
  #   - nazimv.tk
  #   secretName: tls-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
          - containerPort: 80
        command: 
        - sh
        - -c
        - mkdir /usr/local/apache2/htdocs/apache && echo 'Hello from Nazim Apache' > /usr/local/apache2/htdocs/apache/index.html && httpd-foreground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nazim
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        command: 
        - sh
        - -c
        - mkdir /usr/share/nginx/html/nginx && echo 'Hello from Nazim v2' > /usr/share/nginx/html/nginx/index.html && nginx -g 'daemon off;'

