apiVersion: v1
kind: Namespace
metadata:
  name: nazimq
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
    name: myquota
    namespace: nazimq
spec:
  hard:
    cpu: "1"
    memory: 1Gi
    pods: "10"
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: nazimq
spec:
  clusterIP: None
  selector:
    app: mongo-state
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-mongo
  namespace: nazimq
type: Opaque
data:
  username: bmF6aW0=
  password: bmF6aW0xMjM0NQ==


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset-mongo
  namespace: nazimq
spec:
  selector:
    matchLabels:
      app: mongo-state
  serviceName: mongo-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo-state
    spec:
      containers:
      - name: mongo-state
        image: vaheye/mongodb:1
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-mongo
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mongo
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 27017
          name: mongodb
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ping -c 1 localhost
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          exec: 
            command: 
            - /bin/sh
            - -c
            - ping -c 1 localhost
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi  